Repository MusicVillains/Team7-Backend, pull requests merged in 2023-09, with the labels that each got.

#31 Feature/jwt - Refresh 토큰 관련 기능 구현 및 기타 인가처리 구현
  src/main/java/com/teamseven/MusicVillain/Dto/Converter/DateConverter.java
  src/main/java/com/teamseven/MusicVillain/Dto/RequestBody/KakaoOauthLogoutRequestBody.java
  src/main/java/com/teamseven/MusicVillain/Dto/ResponseBody/ResponseObject.java
  src/main/java/com/teamseven/MusicVillain/Member/MemberController.java
  src/main/java/com/teamseven/MusicVillain/Member/MemberService.java
  src/main/java/com/teamseven/MusicVillain/Security/JWT/JwtManager.java
  src/main/java/com/teamseven/MusicVillain/Security/JWT/JwtToken.java
  src/main/java/com/teamseven/MusicVillain/Security/JWT/JwtTokenRepository.java
  src/main/java/com/teamseven/MusicVillain/Security/OAuth/AccessTokenRefreshRequestBody.java
  src/main/java/com/teamseven/MusicVillain/Security/OAuth/OAuthController.java
  src/main/java/com/teamseven/MusicVillain/Security/OAuth/OAuthService.java
  src/main/java/com/teamseven/MusicVillain/Utils/ENV.java
  src/main/resources/logback-spring.xml
Labels: develop

#33 Add authorization processing to methods that require authorization processing
  src/main/java/com/teamseven/MusicVillain/Feed/FeedController.java
  src/main/java/com/teamseven/MusicVillain/Notification/NotificationController.java
Labels: develop

#44 환경 변수 주입 및 초기화 상태 테스트코드 추가
  src/main/java/com/teamseven/MusicVillain/Utils/ENV.java
  src/test/java/com/teamseven/MusicVillain/EnvInjectionTest.java
  src/test/java/com/teamseven/MusicVillain/MusicVillainApplicationTests.java
Labels: test, develop

#59 [+] NotificationServiceUnitTest 구현 완료, NotificationRepository.java 파일명 변경
  src/main/java/com/teamseven/MusicVillain/Feed/FeedService.java
  src/main/java/com/teamseven/MusicVillain/Interaction/InteractionService.java
  src/main/java/com/teamseven/MusicVillain/Member/MemberService.java
  src/main/java/com/teamseven/MusicVillain/Notification/NotificationController.java
  src/main/java/com/teamseven/MusicVillain/Notification/NotificationRepository.java
  src/main/java/com/teamseven/MusicVillain/Notification/NotificationService.java
  src/main/java/com/teamseven/MusicVillain/View/DatabaseViewContorller.java
  src/test/java/com/teamseven/MusicVillain/InteractionServiceUnitTest.java
  src/test/java/com/teamseven/MusicVillain/MemberServiceTest.java
  src/test/java/com/teamseven/MusicVillain/NotificationServiceUnitTest.java
Labels: test, develop

#60 테스트 코드 추가 및 일부 API 추가/변경
  ERD.md
  src/main/java/com/teamseven/MusicVillain/Configuration/WebMvcConfig.java
  src/main/java/com/teamseven/MusicVillain/Dto/RequestBody/InteractionCreationRequestBody.java
  src/main/java/com/teamseven/MusicVillain/Feed/FeedController.java
  src/main/java/com/teamseven/MusicVillain/Feed/FeedService.java
  src/main/java/com/teamseven/MusicVillain/Interaction/InteractionController.java
  src/main/java/com/teamseven/MusicVillain/Interaction/InteractionService.java
  src/main/java/com/teamseven/MusicVillain/Member/MemberService.java
  src/main/java/com/teamseven/MusicVillain/Notification/NotificationController.java
  src/main/java/com/teamseven/MusicVillain/Notification/NotificationRepository.java
  src/main/java/com/teamseven/MusicVillain/Notification/NotificationService.java
  src/main/java/com/teamseven/MusicVillain/Record/RecordController.java
  src/main/java/com/teamseven/MusicVillain/Record/RecordService.java
  src/main/java/com/teamseven/MusicVillain/Security/OAuth/KakaoOAuthLoginRequestBody.java
  src/main/java/com/teamseven/MusicVillain/Security/OAuth/OAuthController.java
  src/main/java/com/teamseven/MusicVillain/Security/OAuth/OAuthService.java
  src/main/java/com/teamseven/MusicVillain/View/DatabaseViewContorller.java
  src/test/java/com/teamseven/MusicVillain/FeedServiceUnitTest.java
  src/test/java/com/teamseven/MusicVillain/InteractionServiceUnitTest.java
  src/test/java/com/teamseven/MusicVillain/MemberServiceTest.java
  src/test/java/com/teamseven/MusicVillain/NotificationServiceUnitTest.java
  src/test/java/com/teamseven/MusicVillain/RecordServiceUnitTest.java
Labels: documentation, test, develop

#64 로그아웃에서 인가처리 일시적으로 비활성화
  src/main/java/com/teamseven/MusicVillain/Security/OAuth/OAuthController.java
  src/main/java/com/teamseven/MusicVillain/Security/OAuth/OAuthService.java
Labels: bug

#71 알림조회 API가 알림에 필요한 정보를 한번에 보내도록 NotificationDto 수정
  src/main/java/com/teamseven/MusicVillain/Dto/Converter/DtoConverterFactory.java
  src/main/java/com/teamseven/MusicVillain/Dto/Converter/NotificationDtoConverter.java
  src/main/java/com/teamseven/MusicVillain/Dto/NotificationDto.java
  src/main/java/com/teamseven/MusicVillain/Notification/NotificationService.java
Labels: develop, refactoring
